data:
  sample_size: 1000
  test_size: 0.2
  random_state: 42

models:
  cv_folds: 5
  scoring: "roc_auc"
  models_to_train: ["logistic", "random_forest", "xgboost"]

api:
  host: "0.0.0.0"
  port: 8000
  debug: true

paths:
  data_raw: "data/raw/sample_patient_data.csv"
  models_dir: "models/saved_models/"
  results_dir: "results/"
